### PR TITLE
release metadata script added

### PR DESCRIPTION
**Pull request by suhaibMo**
In this PR,
`release_metadata.json` file generation based on input arguments of Ensembl versions provided.

### CODE REVIEW

**Review by pcm32 — DISMISSED** [review]
LGTM

**Comment by suhaibMo** [comment]
Thanks @pcm32

**Comment by suhaibMo** [comment]
@pcm32 added another commit to sort file by field names for better readability. Can you review again please. Thanks

**Review by pcm32 — APPROVED** [review]

**Comment by suhaibMo** [comment]
Thanks @pcm32

**Pull request merged**
